import React from 'react';
export function Ledger({state,act}){
 const names=[['GBrain','Incident memory'],['Memorable','Remediation procedure'],['River','Model weights']];
 return <aside className="ledger"><h2 className="eyebrow">Learning ledger</h2><div className="providers">{names.map(([name,description])=><div className="provider" key={name}><strong>{name}</strong><span>{description}</span><small className={state.connections[name]?'verified':''}>{state.connections[name]||(state.configured[name]?'Configured':'Not connected')}</small></div>)}</div><div className="ledger-actions"><button disabled={state.busy||!state.configured.GBrain} onClick={()=>act('connect')}>Connect GBrain</button><button disabled={state.busy||!state.configured.GBrain||!Object.keys(state.corrections).length} onClick={()=>act('sync')}>Sync corrections</button><button disabled={state.busy||!state.configured.GBrain} onClick={()=>act('recall')}>Recall incidents</button></div><Evaluation state={state}/>{state.recall&&<details><summary>Retrieved memory</summary><pre>{JSON.stringify(state.recall,null,2)}</pre></details>}{Object.keys(state.procedures).length>0&&<details><summary>{Object.keys(state.procedures).length} procedure drafts</summary><pre>{JSON.stringify(state.procedures,null,2)}</pre></details>}</aside>
}
export function Evaluation({state}){
 const run=state.runs.at(-1);
 const metric=(stage)=>run?.[stage]?.metrics;
 return <section className="evaluation"><h2>Held-out evaluation</h2><div className="scores">{['baseline','trained'].map(stage=><div key={stage}><span className="eyebrow">{stage}</span><strong className={metric(stage)?'score':''}>{metric(stage)?`${metric(stage).correct} / ${metric(stage).n}`:'Not run'}</strong><span className="muted">{metric(stage)?'correct decisions':''}</span></div>)}</div>{run?.trained&&<p className="delta">{run.trained.metrics.correct-run.baseline.metrics.correct>=0?'+':''}{run.trained.metrics.correct-run.baseline.metrics.correct} correct decisions after training.</p>}<p className="caption">12 fixed synthetic cases. Same prompt and sampling settings before and after. Reference labels are draft labels, not clinical ground truth.</p></section>
}
export function Results({state}){
 const run=state.runs.at(-1), before=run?.baseline?.rows||[], after=run?.trained?.rows||[];
 return <section className="results"><div className="section-top"><h2>What changed?</h2><span className="caption">{run?.checkpoint?'Checkpoint saved':before.length?'Measured on River':''}</span></div><div className="table-scroll"><table><thead><tr><th>Case</th><th>Reference</th><th>Baseline</th><th>Trained</th></tr></thead><tbody>{before.length?before.map((r,i)=><tr key={r.id}><td><span className="case-id">{r.id}</span>{r.title}</td><td><Label value={r.expected}/></td><td><Label value={r.predicted} correct={r.predicted===r.expected}/></td><td>{after[i]?<Label value={after[i].predicted} correct={after[i].predicted===r.expected}/>:<span className="muted">Not run</span>}</td></tr>):<tr><td colSpan="4" className="empty">Run an evaluation to see measured results.</td></tr>}</tbody></table></div>{before.length>0&&<div className="metric-notes">{['baseline','trained'].map(stage=>{const m=run[stage]?.metrics;return m&&<p key={stage}><b>{stage}</b> · Missed escalations {m.missed_escalations}/{m.escalation_cases} · Unnecessary escalations {m.unnecessary_escalations}/{m.acceptable_cases} · Invalid outputs {m.invalid}</p>})}</div>}{run&&<details><summary>Experiment provenance and raw outputs</summary><pre>{JSON.stringify(run,null,2)}</pre></details>}</section>
}
function Label({value,correct}){return <span className={'label '+(correct===true?'good':correct===false?'bad':'')}>{value}</span>}
export function Setup(){return <details className="setup"><summary>Connect your accounts</summary><div className="setup-body"><h3>Run with your hackathon credentials</h3><p>Add your keys to the <code>.env</code> file in the project folder, then restart the Python server. Credentials stay on the server.</p><pre>RIVER_API_KEY=your_key{'\n'}RIVER_MODEL=Qwen/Qwen3.5-9B{'\n'}GBRAIN_TOKEN=your_connection_token{'\n'}MEMORABLE_API_KEY=optional_key</pre><p>GBrain: add the hackathon workspace memory to a client with Full access, then create a token connection. Memorable extraction is optional. Training sends only approved synthetic cases to River.</p><p>The QM tool adapter is included in the source package. QM, Superset, and UFO are not connected to this running app.</p></div></details>}
