import React,{useState} from 'react';
import demoVideo from '../docs/IMMUNE-demo.mp4?url';
export function Arrow({back=false}){return <svg aria-hidden="true" className={back?'arrow back':'arrow'} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 12h15M13 6l6 6-6 6"/></svg>}
function Tag({children,tone=''}){return <span className={`tag ${tone}`}>{children}</span>}
function Field({title,children}){return <div className="field"><h3>{title}</h3><p>{children}</p></div>}
function Download({value,name,children}){function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return <button className="text-button" onClick={download}>{children}<Arrow/></button>}
function outcome(row,after){return row.predicted===after.predicted?'Unchanged':after.predicted===row.expected?'Improved':'Regressed'}
export function Experiment({evidence}){
 const [tab,setTab]=useState('Case explorer'),[filter,setFilter]=useState('All'),[selected,setSelected]=useState('H12');
 const {run}=evidence;
 const rows=run.baseline.rows.map((r,i)=>({...evidence.cases.find(c=>c.id===r.id),before:r.predicted,after:run.trained.rows[i].predicted,change:outcome(r,run.trained.rows[i])})).sort((a,b)=>({Improved:0,Regressed:1,Unchanged:2}[a.change]-{Improved:0,Regressed:1,Unchanged:2}[b.change]));
 const visible=rows.filter(r=>filter==='All'||r.change!=='Unchanged'),current=visible.find(r=>r.id===selected)||visible[0];
 function move(delta){setSelected(visible[(visible.indexOf(current)+delta+visible.length)%visible.length].id)}
 return <section aria-label="Experiment explorer"><div className="toolbar"><div className="tabs" role="tablist" aria-label="Experiment views">{['Case explorer','Training trace'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}</button>)}</div><span className="recorded"><i/>Recorded experiment · Sep 27, 2026</span></div>
 {tab==='Case explorer'?<div className="explorer"><aside className="case-sidebar"><div className="list-heading"><h2>Held-out cases</h2><div className="filters" aria-label="Filter cases">{['All','Changed'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>{setFilter(f);if(f==='Changed')setSelected('H12')}}>{f} {f==='All'?12:2}</button>)}</div></div><div className="case-list">{visible.map(r=><button key={r.id} className={`case-row ${current.id===r.id?'chosen':''}`} aria-pressed={current.id===r.id} onClick={()=>setSelected(r.id)}><span className="case-id">{r.id}</span><span className="case-name"><strong>{r.title}</strong><small>{r.family}</small></span><Tag tone={r.change.toLowerCase()}>{r.change}</Tag></button>)}</div></aside>
 <article className="case-detail" aria-live="polite"><div className="detail-heading"><div><span className="mono">{current.id} / {current.family}</span><h2>{current.title}</h2></div><div className="pager"><button onClick={()=>move(-1)} aria-label="Previous case"><Arrow back/><span>Previous</span></button><button onClick={()=>move(1)} aria-label="Next case"><span>Next</span><Arrow/></button></div></div><h3 className="section-label">Evidence</h3><Field title="Supplied context">{current.context}</Field><Field title="Agent output">{current.output}</Field><div className="comparison"><div className="prediction"><h3>Before training <Tag>{current.before}</Tag></h3><p className="mono">{current.before}</p><small>{current.before===current.label?'Matches reference':'Does not match reference'}</small></div><div className={`prediction ${current.change.toLowerCase()}`}><h3>After training <Tag tone={current.change.toLowerCase()}>{current.after}</Tag></h3><p className="mono">{current.after}</p><small>{current.after===current.label?'Matches reference':'Does not match reference'}</small></div></div><div className="reference"><span>Reference decision <Tag>{current.label}</Tag></span><p>{current.rationale}</p></div><div className="result-note"><strong>The full result</strong><p>One error corrected. One regression exposed.<br/><b>No net accuracy gain.</b></p></div></article></div>:<Trace run={run} source={evidence.source}/>}
 <div className="evidence-bar"><a href={evidence.source} target="_blank" rel="noreferrer">Inspect the original run <Arrow/></a><Download value={evidence} name="immune-experiment.json">Download evidence</Download></div></section>
}
function Trace({run,source}){
 const logs=run.losses.map(Math.log10),max=Math.max(...logs),min=Math.min(...logs),coords=logs.map((v,i)=>`${50+i*680/(logs.length-1)},${30+(max-v)/(max-min)*170}`).join(' ');
 return <div className="trace"><div className="trace-lead"><div><span className="mono">Qwen3.5-9B · LoRA rank {run.lora_rank}</span><h2>A weight update.<br/>An honest result.</h2><p>Twelve updates on twelve approved decisions. The same twelve held-out inputs before and after. Every prediction remains inspectable.</p></div><dl><div><dt>Learning rate</dt><dd>{run.learning_rate}</dd></div><div><dt>Decoding</dt><dd>Greedy · seed {run.seed}</dd></div><div><dt>Invalid outputs</dt><dd>0 before / 0 after</dd></div><div><dt>Missed required escalations</dt><dd>0 before / 0 after</dd></div></dl></div><div className="loss-chart"><div className="section-top"><h3>Training loss</h3><span className="mono">Logarithmic scale · 12 optimizer steps</span></div><svg role="img" aria-label="Training loss falls from 0.269 to 0.00000264 over twelve steps, with an increase at step two" viewBox="0 0 780 235"><line x1="50" y1="30" x2="730" y2="30"/><line x1="50" y1="115" x2="730" y2="115"/><line x1="50" y1="200" x2="730" y2="200"/><polyline points={coords}/>{logs.map((v,i)=><circle key={i} cx={50+i*680/(logs.length-1)} cy={30+(max-v)/(max-min)*170} r="4"><title>{`Step ${i+1}: ${run.losses[i].toPrecision(4)}`}</title></circle>)}<text x="50" y="227">Step 1</text><text x="685" y="227">Step 12</text></svg><p>Lower training loss did not produce a net gain on held-out accuracy.</p></div><details className="provenance"><summary>Checkpoint, hashes &amp; individual losses</summary><dl><dt>Saved checkpoint</dt><dd>{run.checkpoint}</dd><dt>Training data SHA-256</dt><dd>{run.training_sha256}</dd><dt>Held-out data SHA-256</dt><dd>{run.heldout_sha256}</dd></dl><ol>{run.losses.map((loss,i)=><li key={i}>Step {i+1}: <code>{loss.toPrecision(6)}</code></li>)}</ol><a href={source} target="_blank" rel="noreferrer">View run provenance <Arrow/></a></details></div>
}
const storageKey='immune-public-reviews-v1';
export function Review({cases}){
 const [saved,setSaved]=useState(()=>{try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}});
 const [id,setId]=useState('T01'),[label,setLabel]=useState(saved.T01?.label||'REVISE'),[rationale,setRationale]=useState(saved.T01?.rationale||''),[notice,setNotice]=useState('');
 const current=cases.find(c=>c.id===id);
 function select(id){setId(id);setLabel(saved[id]?.label||'REVISE');setRationale(saved[id]?.rationale||'');setNotice('')}
 function save(){const next={...saved,[id]:{case_id:id,label,rationale,at:new Date().toISOString(),source:'Public browser rehearsal; not included in recorded training'}};try{localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);setNotice('Review saved in this browser. It has not been sent to GBrain or used for training.')}catch{setNotice('Browser storage is unavailable. Export your review to keep it.');setSaved(next)}}
 return <section className="review-view"><div className="toolbar"><h2>Try an expert review</h2><span className="mono">{Object.keys(saved).length} saved in this browser</span></div><div className="review-grid"><div><label className="section-label" htmlFor="training-case">Choose a synthetic case</label><select id="training-case" value={id} onChange={e=>select(e.target.value)}>{cases.map(c=><option key={c.id} value={c.id}>{c.id} · {c.title}{saved[c.id]?' · Saved':''}</option>)}</select><Field title="Supplied context">{current.context}</Field><Field title="Agent output">{current.output}</Field><details className="reference-hint"><summary>Show the draft reference</summary><p><Tag>{current.label}</Tag> {current.rationale}</p></details></div><div className="review-form"><h3>Your decision</h3><div className="decisions">{['SHIP','REVISE','ESCALATE'].map(l=><button key={l} className={l===label?'selected':''} aria-pressed={l===label} onClick={()=>setLabel(l)}>{l}</button>)}</div><label htmlFor="rationale">Why this decision?</label><textarea id="rationale" placeholder="Explain what the evidence supports, or where human approval is needed…" value={rationale} onChange={e=>setRationale(e.target.value)} maxLength={4000}/><button className="primary" disabled={!rationale.trim()} onClick={save}>Save review <Arrow/></button><p className="small">This is a browser-only rehearsal. Your review does not change the published experiment.</p>{notice&&<p className="notice" role="status">{notice}</p>}<Download value={saved} name="immune-my-reviews.json">Export my reviews</Download></div></div></section>
}
export function About({evidence}){return <section className="about"><div className="toolbar"><h2>A correction should outlive a conversation.</h2><a href={evidence.source} target="_blank" rel="noreferrer">See the evidence <Arrow/></a></div><div className="about-grid"><div><h3>Remember. Train. Verify.</h3><p>IMMUNE connects expert review to persistent incident memory, procedure drafts, and a controlled training experiment. It separates remembering a correction from proving that a model improved.</p><p>Built by Bryan Tegomoh, a physician and epidemiologist, for the Own Your Intelligence hackathon. The original prototype was built during the event; this public presentation was polished afterward.</p><p className="small">The benchmark is small and synthetic. It does not establish clinical safety or generalization. Training uses decision labels; written rationales remain in memory.</p></div><video controls preload="metadata" playsInline aria-label="IMMUNE recorded workbench demonstration"><source src={demoVideo} type="video/mp4"/>Your browser does not support embedded video. <a href={demoVideo}>Download the demo</a>.</video></div><div className="integrations"><div><span className="integration-number">01</span><h3>GBrain</h3><p>Approved corrections stored with provenance and retrieved from persistent memory.</p><a href={evidence.source} target="_blank" rel="noreferrer">Recorded write &amp; recall <Arrow/></a></div><div><span className="integration-number">02</span><h3>River</h3><p>Real LoRA training, a saved checkpoint, and matched before-and-after evaluation.</p><a href={evidence.source} target="_blank" rel="noreferrer">Completed experiment <Arrow/></a></div><div><span className="integration-number">03</span><h3>Memorable</h3><p>Procedure drafts extracted from task traces. Quality checks exposed limitations that remain visible.</p><a href={evidence.memorySource} target="_blank" rel="noreferrer">Extraction evidence <Arrow/></a></div></div><details className="provenance"><summary>What worked, and what remains unverified</summary><p>The separate Memorable demonstration returned <code>admitted=true</code> with <code>reason=judge_unparseable</code>. All twelve training-run drafts were rejected with <code>no_postcondition</code>. No validated procedure quality is claimed.</p><p>The QM MCP adapter and Superset presentation assets are implemented; live activation is unverified. UFO is not integrated. The presentation does not run paid provider operations. Open the workbench for owner-authorized training and memory operations.</p></details></section>}
